apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-sdk
  labels:
    app: aws-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-sdk-app
  template:
    metadata:
      labels:
        app: aws-sdk-app
    spec:
      containers:
        - name: app
          image: aws-sdk-test
          imagePullPolicy: Never
          command: [ "sleep" ]
          args: [ "infinity" ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: AWS_REGION
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-creds
                key: AWS_SECRET_ACCESS_KEY
          ports:
            - name: http
              containerPort: 3000