# dbinstance-postgres.yaml

dbinstance:
  allocatedStorage: 20
  dbInstanceClass: db.t3.micro
  engine: postgres
  engineVersion: 14
  name: #enter db name

# db-cred-helm.yaml

dbcreds:
  name: #enter db creds name
  username: #enter master username
  password: #enter master password

service:
  type: ClusterIP
  port: 80


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

