apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  host: "{{ .Values.postgresql.sed.host }}"
  port: {{ .Values.postgresql.sed.port | quote }}
  username: "{{ .Values.postgresql.sed.username }}"
  password: "{{ .Values.postgresql.sed.password }}"
  database: "{{ .Values.postgresql.sed.database }}"